# Generated by Django 5.1.7 on 2025-03-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('album_group', models.TextField(blank=True, null=True)),
                ('album_type', models.CharField(max_length=50)),
                ('release_date', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'albums',
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artists',
            },
        ),
        migrations.CreateModel(
            name='AudioFeatures',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('acousticness', models.FloatField(blank=True, null=True)),
                ('analysis_url', models.URLField(blank=True, null=True)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('instrumentalness', models.FloatField(blank=True, null=True)),
                ('key', models.IntegerField(blank=True, null=True)),
                ('liveness', models.FloatField(blank=True, null=True)),
                ('loudness', models.FloatField(blank=True, null=True)),
                ('mode', models.BooleanField(blank=True, null=True)),
                ('speechiness', models.FloatField(blank=True, null=True)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('time_signature', models.IntegerField(blank=True, null=True)),
                ('valence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audio_features',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='RAlbumsArtists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('album_id', models.CharField(max_length=50)),
                ('artist_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'r_albums_artists',
            },
        ),
        migrations.CreateModel(
            name='RAlbumsTracks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('album_id', models.CharField(max_length=50)),
                ('track_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'r_albums_tracks',
            },
        ),
        migrations.CreateModel(
            name='RArtistGenre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_id', models.CharField(max_length=50)),
                ('artist_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'r_artist_genre',
            },
        ),
        migrations.CreateModel(
            name='RTrackArtist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track_id', models.CharField(max_length=50)),
                ('artist_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'r_track_artist',
            },
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('disc_number', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('explicit', models.IntegerField(blank=True, null=True)),
                ('audio_feature_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('is_playable', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
    ]
