# Generated by Django 5.1.7 on 2025-04-18 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistVector',
            fields=[
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.artists')),
                ('vector', models.JSONField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artist_vector',
            },
        ),
        migrations.CreateModel(
            name='PrecomputedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('tempo', models.FloatField()),
                ('valence', models.FloatField()),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
    ]
