# Generated by Django 5.1.7 on 2025-04-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_artistvector_precomputedtrack'),
    ]

    operations = [
    ]
