# Generated by Django 5.1.7 on 2025-04-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_create_precomputedtrack'),
    ]

    operations = [
    ]
