# Generated by Django 5.1.7 on 2025-04-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_update_precomputed_track_db_table'),
    ]

    operations = [
    ]
