# Generated by Django 5.1.7 on 2025-04-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sync_precomputedtrack_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecomputedArtist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField()),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('loudness', models.FloatField()),
                ('speechiness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
            ],
            options={
                'db_table': 'precomputed_artist',
            },
        ),
        migrations.AlterField(
            model_name='precomputedtrack',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='precomputedtrack',
            table='precomputed_track',
        ),
    ]
